import type { AppEvent, Person } from "@/lib/db/types";

const NOW = Date.now();
const DAY = 24 * 60 * 60 * 1000;

// Stable seed ids — prefixed so they're easy to spot in DevTools.
// Schema accepts any string id; ULID-shape is only enforced on user-created rows.
const ID = {
  // People
  sara: "seed:p-sara-kim",
  kareem: "seed:p-kareem-tate",
  mason: "seed:p-mason-lee",
  layla: "seed:p-layla-hassan",
  diego: "seed:p-diego-ortiz",
  priya: "seed:p-priya-patel",
  tomas: "seed:p-tomas-novak",
  aisha: "seed:p-aisha-bello",
  // Events
  reactNyc: "seed:e-react-nyc-meetup",
  aiCairo: "seed:e-ai-tinkerers-cairo",
  designSystems: "seed:e-design-systems-conf",
  founderBrunch: "seed:e-founder-brunch-sf",
} as const;

export const SEED_PEOPLE: Person[] = [
  {
    id: ID.sara,
    name: "Sara Kim",
    role: "Product designer",
    company: "Linear",
    tags: ["design", "nyc", "react"],
    notes: "Loves typography. Looking for a side project.",
    closeness: "close",
    createdAt: NOW - 30 * DAY,
    lastContactAt: NOW - 7 * DAY,
    eventMetId: ID.reactNyc,
  },
  {
    id: ID.kareem,
    name: "Kareem Tate",
    role: "Product manager",
    company: "Notion",
    tags: ["pm", "brooklyn"],
    notes: "Mentioned hiring a designer in Q3.",
    closeness: "warm",
    createdAt: NOW - 60 * DAY,
    lastContactAt: NOW - 14 * DAY,
    eventMetId: ID.reactNyc,
  },
  {
    id: ID.mason,
    name: "Mason Lee",
    role: "Founder",
    company: "(stealth)",
    tags: ["founder", "sf", "ai"],
    notes: "Building something with embeddings. Wants intros to ML folks.",
    closeness: "warm",
    createdAt: NOW - 21 * DAY,
    lastContactAt: NOW - 3 * DAY,
    eventMetId: ID.founderBrunch,
  },
  {
    id: ID.layla,
    name: "Layla Hassan",
    role: "Engineer",
    company: "Anthropic",
    tags: ["engineering", "ai", "cairo"],
    notes: "Met at the AI Tinkerers night. Has a side project around dev tools.",
    closeness: "cooling",
    createdAt: NOW - 90 * DAY,
    lastContactAt: NOW - 45 * DAY,
    eventMetId: ID.aiCairo,
  },
  {
    id: ID.diego,
    name: "Diego Ortiz",
    role: "Product designer",
    company: "Stripe",
    tags: ["design", "nyc", "fintech"],
    notes: "Sharp on payments UX. Open to coffee chats.",
    closeness: "warm",
    createdAt: NOW - 14 * DAY,
    lastContactAt: NOW - 10 * DAY,
    eventMetId: ID.reactNyc,
  },
  {
    id: ID.priya,
    name: "Priya Patel",
    role: "Data scientist",
    company: "Pinecone",
    tags: ["data", "brooklyn", "ai"],
    notes: "Speaks at meetups. Generous with feedback.",
    closeness: "close",
    createdAt: NOW - 50 * DAY,
    lastContactAt: NOW - 1 * DAY,
    eventMetId: ID.aiCairo,
  },
  {
    id: ID.tomas,
    name: "Tomáš Novák",
    role: "Engineer",
    company: "Vercel",
    tags: ["engineering", "prague", "framework"],
    notes: "Wrote a great blog on edge runtimes. Pinged about job openings.",
    closeness: "warm",
    createdAt: NOW - 40 * DAY,
    lastContactAt: NOW - 20 * DAY,
  },
  {
    id: ID.aisha,
    name: "Aisha Bello",
    role: "Founder",
    company: "(stealth)",
    tags: ["founder", "lagos", "creator"],
    notes: "Building a creator-economy product. Looking for design help.",
    closeness: "cooling",
    createdAt: NOW - 120 * DAY,
    lastContactAt: NOW - 70 * DAY,
  },
];

export const SEED_EVENTS: AppEvent[] = [
  {
    id: ID.reactNyc,
    name: "React NYC Meetup",
    date: NOW - 7 * DAY,
    location: "Brooklyn, NY",
    tags: ["meetup", "react"],
    attendees: [ID.sara, ID.kareem, ID.diego],
    status: "attended",
    createdAt: NOW - 30 * DAY,
  },
  {
    id: ID.aiCairo,
    name: "AI Tinkerers Cairo",
    date: NOW - 1 * DAY,
    location: "Cairo",
    tags: ["meetup", "ai"],
    attendees: [ID.layla, ID.priya],
    status: "attended",
    createdAt: NOW - 14 * DAY,
  },
  {
    id: ID.designSystems,
    name: "Design Systems Conf",
    date: NOW + 7 * DAY,
    location: "Online",
    tags: ["conference", "design"],
    attendees: [],
    status: "going",
    createdAt: NOW - 10 * DAY,
  },
  {
    id: ID.founderBrunch,
    name: "Founder Brunch SF",
    date: NOW + 14 * DAY,
    location: "San Francisco",
    tags: ["brunch", "founder", "sf"],
    attendees: [ID.mason],
    status: "interested",
    createdAt: NOW - 5 * DAY,
  },
];
